### ISSUE TITLE
dev_fscrunch_stale: Empty DAT for diced_Parkes_57941_12846_HIP33499_S_fine.h5

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#104]
Looking at the resultant DAT file of FindDoppler.search() on diced_Parkes_57941_12846_HIP33499_S_fine..h5:
* 1.3.1: 158 hits
* dev:    no hits

url for the HDF5 file: http://blpd0.ssl.berkeley.edu/parkes_testing/

**Comment by texadactyl** [comment]
Note that this issue prevents a realistic Travis CI run on a PR.

**Comment by telegraphic** [comment]
Is this still open? 

We could add a test along the lines of:

```python
fd = FindDoppler('diced_Parkes_57941_12846_HIP33499_S_fine.h5')
fd.search()
dat = read_dat('diced_Parkes_57941_12846_HIP33499_S_fine.dat')
assert len(dat) == 158
```

**Comment by texadactyl** [comment]
@telegraphic 

We have plenty of file coverage.  This issue was written up at a time when you were experimenting with the now very stale ```dev_fscrunch_stale``` branch.  The master branch at that time had no issues with the mentioned file and still does not.

My point was this:  
- What do you want to do with that branch?  
- Save it and delete it?  
- Just delete it?  

I did not wish to guess and cause you to lose something that you might have wanted to keep.

**Comment by telegraphic** [comment]
I think it's probably time for me to accept that the branch is too far gone and delete it, so we can close this issue too!

**Comment by texadactyl** [comment]
Done.
