### ISSUE TITLE
turboSETI won´t compile

### ISSUE THREAD

**Issue by hector-noriega** [UCBerkeleySETI/turbo_seti#11]
Good morning,
We are beginning a research collaboration with Dr. Emilio Enriquez (Berkeley SETI), but I´m having issues with turboSETI. I just cannot compile the code on Kubuntu 18.04.

My system basic information:  Ubuntu 18.04.1 LTS, 4.15.0-43-generic, x86_64.

After updating and installing all Python-related programs, I get these errors with two specific files, setup.py (in turboSETI) and Dependencies.py (in my libraries) : 
_____________________________________________________________________
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    ext_modules = cythonize(extensions),
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 967, in cythonize
    aliases=aliases)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 812, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 111, in nonempty
    raise ValueError(error_msg)
ValueError: 'turbo_seti/findoppler/taylor_tree.pyx' doesn't match any files
______________________________________________________________________

I´m frankly new to Python and any help will be greatly appreciated.

Thank you,
Héctor Noriega-Mendoza

**Comment by texadactyl** [comment]
Compiled without errors this way:
 ```python3 setup.py install```

I saw some warnings:

(1) ```site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API```

(2) ```Running blimpy-1.3.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-z2j_f4se/blimpy-1.3.5/egg-dist-tmp-gb8d0ijy
/home/elkins/anaconda3/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'platform' warnings.warn(msg)```

The first one is because one of the dependencies is using a Numpy API which will be unsupported in the future.

The second warning might because this is the first time someone has tried installing into an Anaconda environment.  Maybe?  Or happens all the time?

This worked ok:
```turboSETI -h
Usage: turboSETI <FULL_PATH_TO_FIL_FILE> [options]

Options:
  -h, --help            show this help message and exit
  -M MAX_DRIFT, --max_drift=MAX_DRIFT
                        Set the drift rate to search. Unit: Hz/sec. Default:
                        10.0
  -s SNR, --snr=SNR     SNR threshold. Default: 25.0
  -o OUT_DIR, --out_dir=OUT_DIR
                        Location for output files. Default: local dir.
  -l LOGLEVEL, --loglevel=LOGLEVEL
                        Specify log level (info, debug)
  -c COARSE_CHANS, --coarse_chans=COARSE_CHANS
                        Coma separated list of coarse channels to analyze.(ie.
                        "5,8" to do from 5th to 8th coarse channels)
```

**Comment by texadactyl** [comment]
I tried the h5 file in the ```voyager_test``` subdirectory.  The standard output follows.  Did I miss something?

```
turboSETI Voyager1.single_coarse.fine_res.h5
blimpy.file_wrapper INFO     Skipping loading data ...
root            ERROR    Error accessing header from file: Voyager1.single_coarse.fine_res.h5.
Traceback (most recent call last):
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/data_handler.py", line 147, in __init__
    header = self.__make_data_header(self.fil_file.header)
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/data_handler.py", line 215, in __make_data_header
    base_header[u'SOURCE'] = header[u'source_name'].replace('\xc2\xa0','_').replace(' ','_')
KeyError: 'source_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/seti_event.py", line 75, in main
    find_seti_event = FinDoppler(filename, max_drift = opts.max_drift, snr = opts.snr, out_dir = opts.out_dir,coarse_chans = opts.coarse_chans, obs_info=obs_info)
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/findopp.py", line 56, in __init__
    self.data_handle = DATAHandle(datafile,out_dir=out_dir)
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/data_handler.py", line 49, in __init__
    data_obj = DATAH5(filename)
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/data_handler.py", line 150, in __init__
    raise IOError("Error accessing header from file: %s."%self.filename)
OSError: Error accessing header from file: Voyager1.single_coarse.fine_res.h5.
Traceback (most recent call last):
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/data_handler.py", line 147, in __init__
    header = self.__make_data_header(self.fil_file.header)
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/data_handler.py", line 215, in __make_data_header
    base_header[u'SOURCE'] = header[u'source_name'].replace('\xc2\xa0','_').replace(' ','_')
KeyError: 'source_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/seti_event.py", line 75, in main
    find_seti_event = FinDoppler(filename, max_drift = opts.max_drift, snr = opts.snr, out_dir = opts.out_dir,coarse_chans = opts.coarse_chans, obs_info=obs_info)
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/findopp.py", line 56, in __init__
    self.data_handle = DATAHandle(datafile,out_dir=out_dir)
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/data_handler.py", line 49, in __init__
    data_obj = DATAH5(filename)
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/data_handler.py", line 150, in __init__
    raise IOError("Error accessing header from file: %s."%self.filename)
OSError: Error accessing header from file: Voyager1.single_coarse.fine_res.h5.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elkins/anaconda3/bin/turboSETI", line 11, in <module>
    load_entry_point('turbo-seti==0.7.3', 'console_scripts', 'turboSETI')()
  File "/home/elkins/anaconda3/lib/python3.7/site-packages/turbo_seti-0.7.3-py3.7-linux-x86_64.egg/turbo_seti/findoppler/seti_event.py", line 84, in main
    raise Exception(1,'[turbo_SETI] Some issue with FinDoppler.',e)
Exception: (1, '[turbo_SETI] Some issue with FinDoppler.', OSError('Error accessing header from file: Voyager1.single_coarse.fine_res.h5.'))

```

**Comment by texadactyl** [comment]
Also, make sure that all of the dependency packages (E.g. cython) are installed from a Python 3 perspective: either with pip3 or Anaconda.

**Comment by texadactyl** [comment]
Hector,

I think that you need someone with you who can help you locally.  One thing that I could recommend since I am "flying blind" (cannot see your system in person) is to start over with your Python packages:

```
# Step 1: Go back to "square 1"
rm -rf /home/hnoriega/.local/lib/python*
rm -rf /home/hnoriega/.cache/pip*
sudo apt-get -y purge python-pip python3-pip
# If you see any folder-trees in /usr/local/lib/*python*, get rid of those too: 
#      sudo rm -rf whatever.
# But, be careful.  The rm -rf function is unforgiving.
# Yes, Python package management is messy!  Terrible, even.  But, useful.

# Step 2: Get Ubuntu up-to-date
sudo apt-get -y update
sudo apt-get -y dist-upgrade
sudo apt-get -y autoclean
sudo apt-get -y autoremove

# Step 3: Rebuild package base
sudo apt-get -y install python-pip python3-pip
PKG_LIST="astropy blimpy cython imageio matplotlib numpy pytest" # Complete?
pip3 install $PKG_LIST

# Step 4: Try again.
```
If you see *ANY* error messages in steps 1-4, then you definitely need a Linux person to have a look.  Sorry but I am in Dallas TX which is a long walk from Berkeley CA.

Step 2 is something all *buntu Linux users should be doing periodically because the Ubuntu baseline, unlike Debian (more conservative), lives on the forefront of new Linux component releases.  RPM-based distributions have equivalent Linux package utilities (E.g. Fedora yum) and should be doing the same.

Anyways, I hope you find this note useful.

Richard

P.S. I am a Software Engineer, not an Astrophysics person.  In the latter, I am an on-line student.

**Comment by texadactyl** [comment]
Finally had time to read their code.  It looks like this project might be stuck on Python 2 based on source code even though I got it to work somewhat with Anaconda/Python3 - mystery.  I am installing a new user on my machine to work with Python 2, pip, and this project.  Will report back later.

**Comment by texadactyl** [comment]
I took my own medicine.  I abandoned Anaconda and now am using pip3 with Python3.  All my projects work fine except this one.  I can cythonize the one pyx file (Taylor Series) but I cannot install.

My install symptoms:
```
python3 setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/test-easy-install-15811.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.6/dist-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).
```
Just guessing, but it might be that this project is using a deprecated package management function, ```easy_install```.  

I tried setting the PYTHONPATH ahead of the setup.py execution to where my packages actually are ($HOME/.local/lib/python3.6/site-packages) but something is insisting on finding them in ```/usr/local/lib/python3.6/dist-packages/```.

Stumped for the moment unless the developers can make a suggestion.  Note that README.md gives no guidance for installation to whatever setup package tools they expect to be used.

So, why does it work under Anaconda???  (=:

**Comment by texadactyl** [comment]
I finally got my clean+build+install to work with Python3/pip3.  I modified their setup.py file.
[setup.py.txt](https://github.com/UCBerkeleySETI/turbo_seti/files/2775867/setup.py.txt)

I reported this in a separate issue.

**Comment by texadactyl** [comment]
I cannot find a turboSETI executable after installing with pip3 even though I could after installing with Anaconda.  I am going to explore writing a Python3 program which uses turbo_seti as an included package.

**Comment by texadactyl** [comment]
My simple program:
```
from turbo_seti import seti_event
seti_event.main()
```
Gave it no arguments at all.  Resulting standard output:
```
Please specify a file name 
Exiting.
```
That is exactly what should happen since no command line options were furnished.
When I run my program (essai.py) with an illegal option (-X), I see:
```
Usage: turboSETI <FULL_PATH_TO_FIL_FILE> [options]

essai.py: error: no such option: -X
```
When I ran my program against the supplied Voyager HDF5 file, I turbo_seti diagnosed the file as missing a header field:
```
blimpy.file_wrapper INFO     Skipping loading data ...
root            ERROR    Error accessing header from file: /home/elkins/projects/turbo_seti-master/voyager_test/Voyager1.single_coarse.fine_res.h5.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/turbo_seti/findoppler/data_handler.py", line 147, in __init__
    header = self.__make_data_header(self.fil_file.header)
  File "/usr/local/lib/python3.6/dist-packages/turbo_seti/findoppler/data_handler.py", line 215, in __make_data_header
    base_header[u'SOURCE'] = header[u'source_name'].replace('\xc2\xa0','_').replace(' ','_')
KeyError: 'source_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/turbo_seti/findoppler/seti_event.py", line 75, in main
    find_seti_event = FinDoppler(filename, max_drift = opts.max_drift, snr = opts.snr, out_dir = opts.out_dir,coarse_chans = opts.coarse_chans, obs_info=obs_info)
  File "/usr/local/lib/python3.6/dist-packages/turbo_seti/findoppler/findopp.py", line 56, in __init__
    self.data_handle = DATAHandle(datafile,out_dir=out_dir)
  File "/usr/local/lib/python3.6/dist-packages/turbo_seti/findoppler/data_handler.py", line 49, in __init__
    data_obj = DATAH5(filename)
  File "/usr/local/lib/python3.6/dist-packages/turbo_seti/findoppler/data_handler.py", line 150, in __init__
    raise IOError("Error accessing header from file: %s."%self.filename)
OSError: Error accessing header from file: /home/elkins/projects/turbo_seti-master/voyager_test/Voyager1.single_coarse.fine_res.h5.
Traceback (most recent call last):

  File "<ipython-input-4-5e9907764a5e>", line 1, in <module>
    runfile('/home/elkins/.config/spyder-py3/temp.py', args='/home/elkins/projects/turbo_seti-master/voyager_test/Voyager1.single_coarse.fine_res.h5', wdir='/home/elkins/.config/spyder-py3')

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/elkins/.config/spyder-py3/temp.py", line 3, in <module>
    seti_event.main()

  File "/usr/local/lib/python3.6/dist-packages/turbo_seti/findoppler/seti_event.py", line 84, in main
    raise Exception(1,'[turbo_SETI] Some issue with FinDoppler.',e)

Exception: (1, '[turbo_SETI] Some issue with FinDoppler.', OSError('Error accessing header from file: /home/elkins/projects/turbo_seti-master/voyager_test/Voyager1.single_coarse.fine_res.h5.',))
```

**Comment by texadactyl** [comment]
Ok, you have intrigued me.  I will try all the proposed fixes in issues that I reported or commented on with Python 2.  If that works, then the changes I proposed to setup.py and taylor_tree.pyx are compatible with Python 2 and 3.

Keep in mind: Python 2, as a whole, is deprecated in 2020.  That is why I encouraged @hector-noriega to use it (Sorry, Hector!).

If I get time, I will look at the ```u'source' != b'source'``` issue too.

**Comment by texadactyl** [comment]
Xubuntu 18.04.1
Python 2.7.15rc1
Cython (0.29.3)

The original setup.py had no diagnostics.  Therefore, the issue I observed is probably due to the fact that the project is using an older version of setuptools.  The setup.py changes that I proposed works in both Python 2 and 3 environments.

Running a build on the original taylor_tree.pyx shows the same diagnostics.  Using np.floor() fixes the problem in Python 2 and 3.  It must be related to the Cython version.

**Comment by texadactyl** [comment]
Yes, with Python 2 and pip (2), I get a different execution result although I am missing some HDF5 plugin (instructions?).  
```
python essai.py /home/elkins/projects/turbo_seti-master/voyager_test/Voyager1.single_coarse.fine_res.h5
blimpy.file_wrapper INFO     Skipping loading data ...
blimpy.file_wrapper INFO     Skipping loading data ...
turbo_seti.findoppler.findopp INFO     {u'telescope_id': 6, u'nbits': 32, u'fch1': 8421.386717353016, u'tstart': 57650.78209490741, u'data_type': 1, u'nchans': 1048576, u'ibeam': 1, u'tsamp': 18.253611008, u'rawdatafile': 'guppi_57650_67573_Voyager1_0002.0000.raw', u'foff': -2.7939677238464355e-06, u'DIMENSION_LABELS': array(['frequency', 'feed_id', 'time'], dtype=object), u'src_raj': <Angle 17.16777333 hourangle>, u'src_dej': <Angle 12.183 deg>, u'nbeams': 1, u'az_start': 0.0, u'source_name': 'Voyager1', u'nifs': 1, u'machine_id': 20, u'za_start': 0.0}
turbo_seti.findoppler.findopp INFO     A new FinDoppler instance created!
turbo_seti.findoppler.findopp INFO     Start ET search for /home/elkins/projects/turbo_seti-master/voyager_test/Voyager1.single_coarse.fine_res.h5
turbo_seti.findoppler.findopp INFO     Start searching for coarse channel: 1
root            ERROR    Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/seti_event.py", line 76, in main
    find_seti_event.search()
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/findopp.py", line 88, in search
    self.search_data(target_data_obj)
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/findopp.py", line 102, in search_data
    spectra, drift_indexes = data_obj.load_data()
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/data_handler.py", line 174, in load_data
    self.fil_file.read_data(f_start=self.f_start, f_stop=self.f_stop)
  File "/usr/local/lib/python2.7/dist-packages/blimpy-1.3.5-py2.7.egg/blimpy/waterfall.py", line 156, in read_data
    self.container.read_data(f_start=f_start, f_stop=f_stop,t_start=t_start, t_stop=t_stop)
  File "/usr/local/lib/python2.7/dist-packages/blimpy-1.3.5-py2.7.egg/blimpy/file_wrapper.py", line 435, in read_data
    self.data = self.h5["data"][self.t_start:self.t_stop,:,self.chan_start_idx:self.chan_stop_idx]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python2.7/dist-packages/h5py-2.9.0-py2.7-linux-x86_64.egg/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
IOError: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)
Traceback (most recent call last):
  File "essai.py", line 3, in <module>
    seti_event.main()
  File "build/bdist.linux-x86_64/egg/turbo_seti/findoppler/seti_event.py", line 84, in main
Exception: (1, '[turbo_SETI] Some issue with FinDoppler.', IOError("Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)",))

```
I do not have a directory tree rooted at /usr/local/hdf5/.

I have h5py (2.9.0) installed.  And, I can use h5py in a small program successfully.

This seems to be a current discussion at [https://github.com/h5py/h5py/issues/843](url).  Any ideas for a work-around until h5py is fixed?

**Comment by texadactyl** [comment]
@telegraphic - the ```u'source' != b'source'``` issue is, as you said, one of the many Python migration issues.  This particular code is in h5py (2.9.0).  So, using Python 3 with turbo_seti, at this point, makes no sense at all.  

@hector-noriega - are y'all in Berkeley CA? Take them out for lunch at the Bear's Lair on campus! (=:

In a nutshell, I can use Python 2 and pip to:

- Build & install: python setup.py install
- Execute: turboSETI on the Voyager h5 file which starts fine and then aborts with a trace-back, complaining about: "IOError: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)".  Yes, this is not a turbo_seti project bug.

Net, the only recommended change from me while the project is on Python 2 are:
- Amend the Taylor Series pyx file to use np.floor() in two places in order to use the latest Cython package.
- Amend README.md to specify installation instructions which include how to fix/bypass the h5 plugin issue.

**Comment by texadactyl** [comment]
Language version migration thoughts:
- Even in the days when I was a young lad, the Fortran folks realized that when migrating from "II" to "IV", one had to make it an upwards-compatible migration.
- The Scientific communities might have been better off (more productive) if they had adopted a JVM-based language instead of Python when they began walking away from Fortran.

**Comment by hector-noriega** [comment]
Richard, sorry for this late response and thanks for all the comments and suggestions. I´m back and about to give turboSETI a new try.
Best,
Héctor

**Comment by texadactyl** [comment]
@hector-noriega No worries, mate.  Bottom line suggestions from me:
- Use Python2.  Python3 support seems to be a work in progress.  
- Anaconda support?  This facility is very popular among Astrophysicists.  Maybe.
- Watch out for "IOError: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)".  I would still like to know what went wrong in my Python2 environment.
- If you are geographically near the project team (E.g. all in Berkeley CA), be sure to try and meet up with them in person if you get an opportunity.

All the best to you.
Richard
.

**Comment by texadactyl** [comment]
@hector-noriega - What is your status?  Also, please have a look at
https://github.com/UCBerkeleySETI/turbo_seti/issues/18#issuecomment-459003250
plus the following message.

**Comment by texadactyl** [comment]
@hector-noriega - 

- Stick to Python 2 for the moment.
- The issue "IOError: Can't read data (can't open directory: /usr/local/hdf5/lib/plugin)" is being addressed in blimpy.  Closed issue #16 contains a work-around until blimpy is ready.  

Please try again and see if you can close this issue.

**Comment by texadactyl** [comment]
Compiles fine with Python3.
I used ` python3 setup.py install`.

**Comment by texadactyl** [comment]
@hector-noriega 
See my message from last May.
I think that you can close this issue.

**Comment by hector-noriega** [comment]
Thank you, it's unfortunate that due to so many technical issues with turbo_seti (which we couldn't even run), a long-distance collaboration project with Dr. Enríquez didn't even get started last year. However, I appreciate your help and comments.


I logged into GitHub, but I don't see how I can close my "case". It appears already closed.


HN

________________________________

**Comment by texadactyl** [comment]
Not yet closed.
Down near the bottom, you should see a "Close" button because you are the one who opened this issue.

**Comment by hector-noriega** [comment]
Done.

**Comment by hector-noriega** [comment]
It's done.

________________________________

**Comment by texadactyl** [comment]
Acuerdo!

**Comment by hector-noriega** [comment]
Yes...de acuerdo.

________________________________
