### ISSUE TITLE
Catch n_coarse_chan is None

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/turbo_seti#114]
When number of coarse channels is not set, and isn't a 'magic' number of channels from GBT, this error is raised:
```
(base) obs@blc05:/datax/PX600/GUPPI$ turboSETI guppi_59127_02922_6110606849_1018-426_R_0001.0000.h5 
bshuf filter already loaded, skip it.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/turbo_seti/find_doppler/seti_event.py", line 101, in exec
    precision=1 if args.flag_single_precision == "y" else 2)
  File "/opt/conda/lib/python3.7/site-packages/turbo_seti/find_doppler/find_doppler.py", line 77, in __init__
    self.data_handle = DATAHandle(datafile, out_dir=out_dir, n_coarse_chan=n_coarse_chan, coarse_chans=coarse_chans, kernels=self.kernels)
  File "/opt/conda/lib/python3.7/site-packages/turbo_seti/find_doppler/data_handler.py", line 77, in __init__
    self.data_list = self.__split_h5()
  File "/opt/conda/lib/python3.7/site-packages/turbo_seti/find_doppler/data_handler.py", line 134, in __split_h5
    n_coarse_chan = int(fil_file.calc_n_coarse_chan())
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Suggest catching this and issuing a useful error message for the user, 'Number of coarse channels unknown. Please pass number of coarse channels'.

**Comment by texadactyl** [comment]
What is a magic number and how does it get set?

**Comment by telegraphic** [comment]
The clunky code is in blimpy, here:
https://github.com/UCBerkeleySETI/blimpy/blob/3d6ab63c7ba48d3cebea4db587cd9712acce5894/blimpy/io/base_reader.py#L225

**Comment by texadactyl** [comment]
Agree about the need to have clearer messages.  Which dataset exposed this crash?

**Comment by texadactyl** [comment]
The blimpy utilities are also calling n_coarse_chan() and they all could have the same issue.  Since it is bad news no matter how you look at it, I propose diagnosing/raising this in blimpy/io/base_reader.py.
