### ISSUE TITLE
find_events() is not handling a nil OFF hit table list correctly

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#115]
See line 377 in find_event.py:
```
    off_table = pd.concat(off_table_list,ignore_index=True)        
```
There are cases (E.g. Voyager data) where the off_table_list is nil.  The ON table list is already checked but a nil OFF table list causes pd.concat() to crash: "ValueError: No objects to concatenate"

It would not be difficult to trap the nil list situation and give a more helpful error message.  But, maybe this code could go on with some fix-up.  @telegraphic ?

**Comment by texadactyl** [comment]
This issue needs a scientist to suggest a course of action other than simply giving a more helpful error message.

**Comment by stevecroft** [comment]
The code should proceed even if the OFF table is empty. Valid events can consist of hits in ON tables, and empty OFF tables (as is the case with the single coarse channel Voyager 2020 test cadence).
