### ISSUE TITLE
turbo-seti is out of date on pypi 

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#124]
### Describe the bug
"turbo-seti" is out of date on pypi. 

### To Reproduce
```pip3 uninstall -y turbo_seti```
```pip3 install turbo-seti # from pypi ```
Note that the installed version is less than 2.0.0

### Remediation Suggestion
 @telegraphic - Please do one of the following:
* Update turbo-seti on pypi.
* Delete turbo-seti from pypi i.e. stop using pypi.

It is not hard to stop using pypi because the following command is equivalent to installing turbo-seti from pypi:
```pip install -U git+https://github.com/UCBerkeleySETI/turbo_seti```

**Comment by telegraphic** [comment]
Hey @texadactyl, Working through some of these today -- https://pypi.org/project/turbo-seti/!
