### ISSUE TITLE
README.md should change dependency "pyximport" to "cython"

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#13]
The pyximport function is part of cython.
Cython, in any case, is a dependency.

**Comment by texadactyl** [comment]
While you are at this, please advise what other dependencies need to be fulfilled and how to do so.
E.g. hdf5 plugin

**Comment by texadactyl** [comment]
Okay, hdf5plugin is covered by blimpy.

Blimpy needs no special github mention; it is part of Pypi.org, accessible through ```pip3```.

The original issue still exists.  So easy to fix!

**Comment by telegraphic** [comment]
An easy one indeed - closing issue!
