### ISSUE TITLE
Attempts to implicit conversions of double to long in taylor_tree.pyx

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#15]
Xubuntu 18.04.1
Python 3.6.7
Cython 0.29.3

When cythonizing taylor_tree.pyx, the following diagnostics occur:
```
python3 setup.py build
Compiling turbo_seti/findoppler/taylor_tree.pyx because it changed.
[1/1] Cythonizing turbo_seti/findoppler/taylor_tree.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        nchn         : number of frequency channels (long int)
    '''

    assert outbuf.dtype == DTYPE

    cdef long nsamp = (mlen/nchn) - (2*nchn)
                                 ^
------------------------------------------------------------

turbo_seti/findoppler/taylor_tree.pyx:34:34: Cannot assign type 'double' to 'long'

Error compiling Cython file:
------------------------------------------------------------
...

    cdef DTYPE_t itemp

    for istages in range(0, nstages):
        nmem  *= 2
        nsec1  = nchn/nmem
                    ^
------------------------------------------------------------

turbo_seti/findoppler/taylor_tree.pyx:58:21: Cannot assign type 'double' to 'int'
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    ext_modules=cythonize(extensions, compiler_directives={'language_level': 3.7}),
  File "/home/elkins/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
    cythonize_one(*args)
  File "/home/elkins/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: turbo_seti/findoppler/taylor_tree.pyx

```

Solutions:
Line 34: ```     cdef long nsamp = np.floor((mlen/nchn) - (2*nchn))```
Line 58 ```     nsec1  = np.floor(nchn/nmem)```

**Comment by texadactyl** [comment]
It's probably a cython version issue.  My proposed solution works in Python 2 and 3.  Admittedly, I haven't tried changing the target type to unsigned 64-bit integer.  This could cause new interesting side effects (=:

**Comment by dmkunsman** [comment]
@texadactyl is this still an open issue?  Is there anything I can do to help with this?

**Comment by texadactyl** [comment]
As @jeenriquez classified this issue, it is an enhancement.  It will probably be a bug after migration to Python 3 if no recoding is performed.  

My proposed solution, as I stated earlier, works in Python 2 and 3, regardless of Cython version, because the proposed code performs an explicit type conversion.  However, I will defer the final decision on this issue to the UCBerkeleySETI/turbo_seti project team.
