### ISSUE TITLE
ReadMe.md question

### ISSUE THREAD

**Issue by dmkunsman** [UCBerkeleySETI/turbo_seti#19]
In the section bl internals in the readme.md
I noticed there was no -p argument in seti_event.py.  Just wondering if this is deprecated or not?  Also I didn't see an argument that lets you print waterfall plots.  Was this when turboSETI was using .fil files instead of .h5?
$ python seti_event.py /datax/eenriquez/voyager_test/blc07_guppi_57650_67573_Voyager1_0002.gpuspec.0000.fil -p <your_test_folder> -M 2

**Comment by telegraphic** [comment]
Sorry we kept you hanging on this one. A student is working on improving the plotting scripts, so I am closing this now.
