### ISSUE TITLE
Sorting h5's / dat's by tstart in find_event_pipeline, plot_event_pipeline to avoid out-of-order searching and plotting issues

### ISSUE THREAD

**Issue by ewhite42** [UCBerkeleySETI/turbo_seti#197]
I ran into an issue recently where I attempted to create plots of turboSETI candidate events in data from observations of the Mars2020 spacecraft using plot_event, and when I ran this code: 

```
import glob
from turbo_seti.find_event.plot_event_pipeline import plot_event_pipeline
from turbo_seti.find_event.find_event_pipeline import find_event_pipeline
DATADIR = '/datax/scratch/ewhite/voyager_data/'

dat_list = [DATADIR+'spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66265_DIAG_Mars2020_0011.rawspec.0000.dat',
            DATADIR+'spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66578_DIAG_Mars_0012.rawspec.0000.dat',
            DATADIR+'spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_66892_DIAG_Mars2020_0013.rawspec.0000.dat',
            DATADIR+'spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67205_DIAG_Mars_0014.rawspec.0000.dat',
            DATADIR+'spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67519_DIAG_Mars2020_0015.rawspec.0000.dat',
            DATADIR+'spliced_blc10111213141516o7o0212223242526o7o031323334353637_guppi_59256_67832_DIAG_Mars_0016.rawspec.0000.dat']

# This writes the dat files into a .lst, as required by the find_event_pipeline
with open(DATADIR + 'dat_files.lst', 'w') as f:
    for item in dat_list:
        f.write("%s\n" % item)
PATH_CSVF = 'voyager_snr10_f3.csv'
event_df = find_event_pipeline(DATADIR + 'dat_files.lst',
                               filter_threshold = 3,
                               on_off_first = 'OFF',
                               number_in_cadence = len(dat_list),
                               user_validation=False,
                               saving=True,
                               csv_name=PATH_CSVF)
# We need to create a .lst of the .h5 files, so lets go ahead and do that:
filelist = glob.glob(DATADIR + '*.h5')
# Write file locations to a .lst
with open(DATADIR + 'filelist.lst', 'w') as f:
    for item in filelist:
        f.write("%s\n" % item)
# and finally we plot
plot_event_pipeline(PATH_CSVF,
                    DATADIR + 'filelist.lst',
                    user_validation=True)
```
I noticed that the 6 plots in the cadence were plotted out of order (i.e., the later plots in the sequence were plotted on top of earlier plots, so the drifting signal looked as if it had been shifted oddly). After some troubleshooting I found out that the plots were out of order because plot_event_pipeline seems to expect the list of files in 'filelist.lst' to be in the correct order, instead of sorting it itself in order of the timestamp of each scan in the cadence. I have noticed similar issues before with find_event_pipeline as well, where known events (like Voyager) would not be picked up due to files being listed out of order. I am curious if it would be possible to add functionality to find_event_pipeline and / or plot_event_pipeline that will automatically sort the lists of .dat and .h5 files (respectively) before searching for or plotting the events? I think this would be especially helpful for new users who may not realize that the order in which the plots are listed matter (especially in the case where using glob to create a list of files could create an out-of-order listing). Thanks so much for considering this!

**Comment by texadactyl** [comment]
Unfortunately, plot_event_pipeline uses a duplicate h5 list stored in an external file (2nd parameter) even though it has the names of the h5 files in the CSV (1st parameter)!  ):

Anyways, sorting has been implemented in both find_event_pipeline and plot_event_pipeline.
The default is to sort lists in tstart order.
Running regression tests now.
