### ISSUE TITLE
reverse32bit findopp.py 

### ISSUE THREAD

**Issue by dmkunsman** [UCBerkeleySETI/turbo_seti#20]
I was wondering if this piece of code in finopp.py still needs testing?  Is there any help I can assist with this?
def bitrev3(x):
    raise DeprecationWarning("WARNING: This needs testing.")

    x = ((x & 0x55555555) << 1) | ((x & 0xAAAAAAAA) >> 1)
    x = ((x & 0x33333333) << 2) | ((x & 0xCCCCCCCC) >> 2)
    x = ((x & 0x0F0F0F0F) << 4) | ((x & 0xF0F0F0F0) >> 4)
    x = ((x & 0x00FF00FF) << 8) | ((x & 0xFF00FF00) >> 8)
    x = ((x & 0x0000FFFF) << 16) | ((x & 0xFFFF0000) >> 16)
    return x

**Comment by telegraphic** [comment]
Not 100% sure what this code was for, or if it is used in the main code (the original author has moved on to a new project). Will look into it

**Comment by texadactyl** [comment]
@telegraphic 

```bitrev3``` is defined in 2 different source files:
1. findoppler/helper_functions.py
2. findoppler/findopp.py

Nobody is actually calling ```bitrev3```.  Ditto for ```bitrev2```.

There is a ```bitrev``` function defined in findopp.py that is used internally by ```search_data```.

There is a ```bitrev``` function defined in findoppler/helper_functions.py that nobody is calling.

**Comment by texadactyl** [comment]
I would remove the superfluous source code and just keep bitrev() in search_data.

**Comment by telegraphic** [comment]
Thanks @texadactyl -- agreed that bitrev3 and 2 are not called. I have removed bitrev2 (looks like this was just a slower alternative) and bitrev3.
