### ISSUE TITLE
Make `-h` option outputs version number

### ISSUE THREAD

**Issue by wfarah** [UCBerkeleySETI/turbo_seti#203]
A fast/easy way to check the turboSETI version installed

**Comment by texadactyl** [comment]
Believe it or not, this issue is not simple. Not impossible but might involve structure changes to the package.

Even though a user can do this with the installed package:

**Comment by wfarah** [comment]
Ohh goodie... Not sure if it's a good practice, but can the `-h` execute the following:

```
import os
os.system("python -c \"from turbo_seti import __version__ as TS_VERSION; print(TS_VERSION)\"")
```

**Comment by wfarah** [comment]
Or even better:

```
import os,sys
os.system("%s -c \"from turbo_seti import __version__ as TS_VERSION; print(TS_VERSION)\"" %sys.executable)
```
This way it uses the same executable that `turboSETI` is using

**Comment by wfarah** [comment]
@texadactyl. Also, on second thought, it's probably better to make this `-v` `--version` flags, rather than making it print the version number with `-h` `--help`. This would make it a nicer way to log things, by just calling `turboSETI -v` at a high level
