### ISSUE TITLE
github actions: The build-gpu action always fails

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#240]
https://github.com/UCBerkeleySETI/turbo_seti/blob/master/.github/workflows/push_docker.yml

"No runner matching the specified labels was found: nvidia-gpu"

I realise that ```nvidia-gpu``` is a runner that we are waiting for (yes?).

Suggestion:  Comment out the ```build-gpu``` step until we have a reasonable chance of it succeeding.

**Comment by luigifcruz** [comment]
Looks good to me.
