### ISSUE TITLE
find_doppler.py / helper_functions mixup: median or mean value sought?

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#244]
In helper_functions.py:comp_stats(), the comment says a mean is being calculated but the code retrieves a median from numpy.

In find_doppler.py:search_coarse_channel(), it thinks that comp_stats is returning the mean.

I am not going to change the function from median to mean.  I will however correct the comments and variable names to indicate that a median is being used for the sake of consistency.

Does a radio astronomer disagree?  @telegraphic ?

**Comment by telegraphic** [comment]
Hey @texadactyl -- looks like you've been busy! First of a few responses:

median is better in this case as it's less susceptible to outliers from radio interference. Agree that changing for consistency is the right approach.

**Comment by texadactyl** [comment]
Thanks!
