### ISSUE TITLE
Small issue in the turbo_SETI tutorial

### ISSUE THREAD

**Issue by pranavp25** [UCBerkeleySETI/turbo_seti#276]
**make_table doesn't exist**

I was running the tutorial on my computer and ran into an error while making the Pandas dataframe (In [17])
I looked through the package and it turns out, make_table doesn't exist.

```
from turbo_seti.find_event.find_event import make_table

df = make_table(DATADIR + 'diced_Parkes_57941_12846_HIP33499_S_fine.dat')
df

```
Instead, it looks like read_dat performs a similar functionality

```
from turbo_seti.find_event.find_event import read_dat

df = read_dat(DATADIR + 'diced_Parkes_57941_12846_HIP33499_S_fine.dat')
df
```

Just thought I would point this out so anyone running the tutorial wouldn't be stuck.

Thanks!

**Comment by texadactyl** [comment]
@pranavp25 Good catch and suggested fix.  Yes, the read_dat and make_table functions were combined last December.  This anomaly was noty caught simply because the tutorial is not part of the regression tests.  I'll take care of this tomorrow.
