### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by gijzelaerr** [UCBerkeleySETI/turbo_seti#3]
since releases are good.

**Comment by jeenriquez** [comment]
doing this now in some sort of way. Closing.

**Comment by gijzelaerr** [comment]
thanks! I don't see a release yet though :)

**Comment by telegraphic** [comment]
Hi @gijzelaerr -- is this what you were after? https://github.com/UCBerkeleySETI/turbo_seti/releases

**Comment by gijzelaerr** [comment]
yes! that wasn't there last time I checked.

thanks!

**Comment by telegraphic** [comment]
That's probably because I only just added it, once I realized what you were looking for!
