### ISSUE TITLE
Exposing `offset` to plotSETI users

### ISSUE THREAD

**Issue by wfarah** [UCBerkeleySETI/turbo_seti#305]
A nice addition to `plotSETI` would be allowing users to "offset" the line of best guess, in the pngs, from where turboSETI thinks a hit is detected. This would be useful when trying to plot faint events. The edit would be adding a command line argument to plotSETI that would expose this feature.

The relevant function is here:
https://github.com/UCBerkeleySETI/turbo_seti/blob/master/turbo_seti/find_event/run_pipelines.py#L220-L225

**Comment by texadactyl** [comment]
""offset" the line of best guess from where turboSETI thinks a hit is detected" = ?

**Comment by wfarah** [comment]
Essentially this line:
https://github.com/UCBerkeleySETI/turbo_seti/blob/master/turbo_seti/find_event/run_pipelines.py#L224

and function docstring:
https://github.com/UCBerkeleySETI/turbo_seti/blob/767d5c2a9106f2ebccc4d7f8f6841532ad15b543/turbo_seti/find_event/plot_event_pipeline.py#L58-L65

**Comment by texadactyl** [comment]
So, you just want this parameter exposed at the plotSETI level.
