### ISSUE TITLE
.txt files for h5 files list and dat files list not being written to

### ISSUE THREAD

**Issue by k-perez** [UCBerkeleySETI/turbo_seti#313]
In `run_pipelines.py`, the fh_h5 and fh_dat files need to be closed so that the .txt files that are being written to are actually saved.  

Fix: Add a `fh_h5.close() `and `fh_dat.close()`

**Comment by texadactyl** [comment]
Cannot reproduce reported symptoms.  Adding a fh_h5.close() and fh_dat.close() has no effect since Python run-time automatically closes the file when program flow leaves the "with" context.

**Comment by texadactyl** [comment]
Before getting into the weeds of the source code,
* What was the original `plotSETI` command line?
* Which BL compute node were you on?
* Which directory were you in when executing `plotSETI`?  
* Where were the .h5 files and .dat files?
