### ISSUE TITLE
docs for helper_functions has nil content

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#41]
Fix: In turbo_seti/docs/find_doppler.rst
change
``` .. automodule:: turboseti.find_doppler.helper_functions```
to
``` .. automodule:: turbo_seti.find_doppler.helper_functions```

It's a pity that ```sphinx-build``` did not flag object not found or something to that effect.

**Comment by telegraphic** [comment]
Thanks, my eyes had glazed over and I didn't notice the typo!
