### ISSUE TITLE
Cannot handle any HDF5 whose size exceeds 256 MB

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#46]
Function __make_data_header in class DATAH5 crashes in the coarse channel case.

**Gross symptom:**
```
Traceback (most recent call last):
  File "/home/elkins/.local/lib/python3.8/site-packages/turbo_seti/find_doppler/data_handler.py", line 184, in __init__
    header = self.__make_data_header(self.fil_file.header,coarse=True)
  File "/home/elkins/.local/lib/python3.8/site-packages/turbo_seti/find_doppler/data_handler.py", line 287, in __make_data_header
    base_header['FCNTR'] = np.abs(self.f_stop - self.f_start)/2. + np.min(self.f_start, self.f_stop)
  File "<__array_function__ internals>", line 5, in amin
  File "/home/elkins/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2792, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/home/elkins/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
  File "/home/elkins/.local/lib/python3.8/site-packages/numpy/core/_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

```
**Fix to existing code:**
Line 287 in data_handler.py
```
base_header['FCNTR'] = np.abs(self.f_stop - self.f_start)/2. + np.min(self.f_start, self.f_stop)
```
should be
```
base_header['FCNTR'] = np.abs(self.f_stop - self.f_start)/2. + np.fmin(self.f_start, self.f_stop)
```

Numpy function fmin should be used with integer and floating-point arguments.

**Comment by david-macmahon** [comment]
I think a preferable way to calculate `FCNTR` would be:

    FCNTR = fch1 + f_off * (nchans - 1)/2.0

No `abs()` or `min()` needed and (IMHO) the intent is clearer, but I don't know if these filterbank header values are carried into the HDF5 headers or the Python class.

**Comment by texadactyl** [comment]
They are carried forward.  Here is the header for the monster that is still running:
```
--- File Info ---
DIMENSION_LABELS : [b'frequency' b'feed_id' b'time']
        az_start :                              0.0
       data_type :                                1
            fch1 :                2802.83203125 MHz
            foff :      -2.7939677238464355e-06 MHz
      machine_id :                               20
           nbits :                               32
          nchans :                        359661568
            nifs :                                1
     source_name :                         HIP66077
         src_dej :                     16:48:41.008
         src_raj :                     13:32:44.376
    telescope_id :                                6
           tsamp :                     18.253611008
   tstart (ISOT) :          2017-03-18T08:40:42.000
    tstart (MJD) :               57830.361597222225
        za_start :                              0.0

Num ints in file :                               16
      File shape :               (16, 1, 359661568)
--- Selection Info ---
Data selection shape :               (16, 1, 359661568)
Minimum freq (MHz) :               1797.9492215439677
Maximum freq (MHz) :                    2802.83203125
```
I hadn't thought about it since I am still green on the subject of frequency arrays, coarse or fine.  Sometimes I wish that you, @telegraphic and others were down the hall from me so I could ask questions.

**Comment by texadactyl** [comment]
Note that other h5 files like Voyager do not run into this issue because they take a non-coarse route through the same function in the FITS header construction.  I haven't learned yet why - on my list!  Still reading Danny's radio telescope references.

**Comment by texadactyl** [comment]
Found it.  If an h5 file size exceeds a limit (currently 256MB), it is split into coarse channels.  The monster (16GB) is a good candidate.  Voyager is only 64MB so no splitting into coarse channels.

**Comment by texadactyl** [comment]
@david-macmahon  Your formula for the coarse case is similar to the non-coarse calculation:
```
base_header['FCNTR'] = float(header['fch1']) + header['foff'] * base_header['NAXIS1'] / 2
```

**Comment by texadactyl** [comment]
The f_start and f_stop values are calculated before the subject function is called in another function called ```__split_h5``` (also in data_handler.py).

**Comment by texadactyl** [comment]
@telegraphic 
I should have noted at the top that this bug prevents turbo_seti from handling any HDF5 whose size exceeds 256MB.  Note that eliminates quite a few of the HDF5 files in the Breakthrough open data archive.
