### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by gijzelaerr** [UCBerkeleySETI/turbo_seti#5]
Currently, the code doesn't have a license.

**Comment by jeenriquez** [comment]
I check a little bit on this. I would like to add the MIT license. Not sure if I need anything else but updating setup.py. Do you know @gijzelaerr ?

**Comment by telegraphic** [comment]
@jeenriquez There's some stuff built-in to github for licenses, I just created one (see the automatic pull request). I think MIT is a good choice

**Comment by jeenriquez** [comment]
Thanks a lot @telegraphic! Closing this since resolved.
