### ISSUE TITLE
Ver 1.3.0 data_handler.py fails to enforce size_limit parameters

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/turbo_seti#61]
Classes DATAHandle and DATAH are initialized with size_limit parameters (default: 256 MB).  However, those parameters are never used.  They should be enforced or the parameters should be removed.  

@telegraphic - should size limits be enforced or not?

Other observations:
* line 6: from pkg_resources import resource_filename has a duplicate definition
* lines 110, 184, and 194: The formatted message should be defined once and used in logger and raise.
* The imports should be re-ordered: (a) system packages, (b) pypi packages, (c) SETI imports.

**Comment by telegraphic** [comment]
Removal seems prudent -- we can add them back in if a use case motivated it.

**Comment by texadactyl** [comment]
Ok, tomorrow I'll remove the size_limit parameters unless you do it first.
