### ISSUE TITLE
Add 6-observation cadence data to data archive

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/turbo_seti#67]
Need test data for plot_event, @Sofysicist has some data that can be used for this

**Comment by ssmith00** [comment]
Here are some links to a cadence that is currently on the data archive:
http://blpd8.ssl.berkeley.edu/dl2/Parkes_57941_12846_HIP33499_S_fine.h5
http://blpd8.ssl.berkeley.edu/dl2/Parkes_57941_13194_HIP33499_R_fine.h5
http://blpd8.ssl.berkeley.edu/dl2/Parkes_57941_13542_HIP33499_S_fine.h5
http://blpd8.ssl.berkeley.edu/dl2/Parkes_57941_13884_HIP33499_R_fine.h5
http://blpd8.ssl.berkeley.edu/dl2/Parkes_57941_14233_HIP33499_S_fine.h5
http://blpd8.ssl.berkeley.edu/dl2/Parkes_57941_14584_HIP33499_R_fine.h5

**Comment by texadactyl** [comment]
The very large size is why @ssmith00 diced them:
URL:  'http://blpd0.ssl.berkeley.edu/parkes_testing/'
diced_Parkes_57941_12846_HIP33499_S_fine.h5 (49M)
diced_Parkes_57941_13194_HIP33499_R_fine.h5 (49M)
diced_Parkes_57941_13542_HIP33499_S_fine.h5 (49M)
diced_Parkes_57941_13884_HIP33499_R_fine.h5 (49M)
diced_Parkes_57941_14233_HIP33499_S_fine.h5 (49M)
diced_Parkes_57941_14584_HIP33499_R_fine.h5 (49M)

Those are what we are using in test_pipelines.py now.
