### ISSUE TITLE
warnings or errors and why?

### ISSUE THREAD

**Issue by ngizani** [UCBerkeleySETI/turbo_seti#7]
Is these:

Extracting turbo_seti-0.7.2-py3.6-linux-x86_64.egg to /home/ngizani/anaconda3/lib/python3.6/site-packages
  File "/home/ngizani/anaconda3/lib/python3.6/site-packages/turbo_seti-0.7.2-py3.6-linux-x86_64.egg/turbo_seti/findoppler/find_candidates.py", line 163
    print 'NOTE: Found no hits above the SNR cut.'
                                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'NOTE: Found no hits above the SNR cut.')?

  File "/home/ngizani/anaconda3/lib/python3.6/site-packages/turbo_seti-0.7.2-py3.6-linux-x86_64.egg/turbo_seti/findoppler/plot_candidates.py", line 99
    print target
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int target)?

something to worry about? Thank you

**Comment by telegraphic** [comment]
Does seem to be a Py3 issue, this gets caught in Travis-CI testing: https://travis-ci.org/UCBerkeleySETI/turbo_seti/builds/409508392

**Comment by gijzelaerr** [comment]
@telegraphic is this still an issue?

**Comment by jeenriquez** [comment]
Closing this for now, @ngizani  you could open it again if you still have the issue.

**Comment by ngizani** [comment]
Will let you know at some point @jeenriquez . Thanks!
