### ISSUE TITLE
xticks error in make_waterfall_plots

### ISSUE THREAD

**Issue by rtraas** [UCBerkeleySETI/turbo_seti#72]
`Plot_event.make_waterfall_plots` formats `xticks(np.arange(f_start, f_stop, delta_f/4.), ['','','',''])`, but produces an error due to `np.arange` not being the same length as `['','','','']`.

**Comment by texadactyl** [comment]
@rtraas I have a pull request outstanding that removed an unused parameter in make_waterfall_plots().  This would impact your test programs.  Speaking of plot_event.py testing, your test program(s) would increase coverage of turbo_seti as a whole.  Feel free to contact me on slack as to how we could go about integrating.

**Comment by texadactyl** [comment]
Fixed with merging of PR #73
