### ISSUE TITLE
Algorithm improvement: average across channels for large drift rates.

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/turbo_seti#76]
This proposal is to improve the turboseti algorithm by averaging across channels for large drift rates.

For large drift rates, the signal smears across multiple channels. For example, consider data with 1 Hz resolution and 10 s integrations. If a narrowband signal has a drift rate is greater than `1 Hz / 10 s = 0.1 Hz/s`, then the signal will cross into a neighboring channel. We can therefore improve sensitivity by averaging the two neighboring channels together. We should do this iteratively, averaging data across channels when `channel_resolution / integration_time < drift_rate`. 

This would have to be done in the [search_coarse_channel](https://github.com/UCBerkeleySETI/turbo_seti/blob/3f55c077e4eedd022c5c5d49571e065757455e3b/turbo_seti/find_doppler/find_doppler.py#L143) method, there is a loop over drift rates:

```python
...
    # --------------------------------
    # Looping over drift_rate_nblock
    # --------------------------------
    drift_rate_nblock = int(np.floor(max_drift / (data_obj.drift_rate_resolution * tsteps_valid)))

    ##EE-debuging        kk = 0

    for drift_block in range(-1 * drift_rate_nblock, drift_rate_nblock + 1):
...
```

**Comment by texadactyl** [comment]
@telegraphic 

Isn't this what the original code author intended with the introduction of the "shoulder"/"tdwidth" concept (issue #98, ignoring the FITS metadata names)?  What you stated above seems to be a different "shoulder" approach.  

It would have been useful if the original code author had made the shoulder size a parameter in order to try out the existing "tdwidth" approach.  Is there a design for that approach available anywhere?

**Comment by texadactyl** [comment]
@telegraphic 

I've looked at the ```drift block main loop```, ```hitsearch```, and ```tophitsearch```.  There does not seem to be a safe & effective place to implement this "shoulder" algorithm, given that we need the power values from the adjacent frequency columns in spectra column sequence.  

In the ```drift block loop```, one needs the ```complete_drift_range``` array of drift rates but that is only defined for the current drift block in the loop.  

Yesterday, I made another pass at cleanup (issue #274).  The ```find_doppler.py``` code is  an unpleasant reading experience!  At least the ```data_handler.py``` code is easy to read, warts and all.

**Comment by texadactyl** [comment]
@telegraphic

**Comment by texadactyl** [comment]
I understand that your criteria is a drift rate > 0.1 Hz/s.  But, one keeps doing this throughout the coarse channel until there are no more instances meeting that criteria?

**Comment by telegraphic** [comment]
Note: this was related to the ill-fated PR https://github.com/UCBerkeleySETI/turbo_seti/pull/101

This is however implemented in hyperseti

**Comment by texadactyl** [comment]
Deferred to hyperseti.
