### ISSUE TITLE
polarized turboseti

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/turbo_seti#84]
(needs polarized blimpy support, but adding here as feature request).

Essentially should search stokes I, Q U and V separately.

**Comment by david-macmahon** [comment]
And it should be aware of whether the file contains Stokes parameters I, Q, U, V or auto/cross polarization products XX*, YY*, Re(XY*), Im(XY*) or LL*, RR*, Re(LR*), Im(LR*).

**Comment by dmkunsman** [comment]
Is this still worth trying to work on?  I would like to give it a go.

**Comment by texadactyl** [comment]
@telegraphic @david-macmahon @siemion @stevecroft 

Given hyperseti concept, is it really worth the time & energy to make a major enhancement to turbo_seti and blimpy?

Does Seti BL have the resource bandwidth to entertain multiple parallel tracks of new development?

What is the Seti BL 5-year software plan?  Where should new investments be applied to?
* blimpy/turbo_seti ?
* machine learning seti ?
* hyperseti ?

I'd really like to understand where Seti BL priorities lay.  That is the first step towards development, documentation, and managment of a software budget.  Yes, I came from industry.  

Thank you for your patience. 

Richard

cc: @luigifcruz

**Comment by texadactyl** [comment]
I am going to guess that the following is the current polarisation processing strategy:
* Front-ends (E.g. rawspec, certain hashpipe apps) produce single polarisation files for turbo_seti & blimpy.
* Hyperseti is the go-to multipolarisation search utility of the future.

So, I am closing this issue for turbo_seti & blimpy.

Of course, this is still a potential subject of discussion.
