### ISSUE TITLE
python setup.py clean calls cython

### ISSUE THREAD

**Issue by gijzelaerr** [UCBerkeleySETI/turbo_seti#9]
```
$  python setup.py clean
Compiling turbo_seti/findoppler/taylor_tree.pyx because it changed.
[1/1] Cythonizing turbo_seti/findoppler/taylor_tree.pyx
running clean
```

this is not expected when you actually want to clean the repository.

**Comment by jeenriquez** [comment]
Is this still an issue? I'm not sure how to solve it. @gijzelaerr any suggestions?

**Comment by texadactyl** [comment]
When I use Python 3, I see exactly the following:
```
python3 setup.py clean
running clean
removing 'build/temp.linux-x86_64-3.7' (and everything under it)
```
Looks "clean" to me.  Sorry about the pun!

**Comment by texadactyl** [comment]
I really try to stay away from Python 2 executions (install, clean, etc.) because within 12 months, bye bye Python 2.  Unsupported.

**Comment by texadactyl** [comment]
There seems to be no way to get the setup procedure to recognize/process "clean".

If you would like a "clean" function, I would recommend a technique which I have done before in other Python projects.  Edit ```setup.py``` and do the following:

1. Just before current line 1, insert:
```
import subprocess
import sys
```

2. Just before the ```setup()``` call, insert the following code block:
```
if len(sys.argv) == 2:
    if sys.argv[1] == "clean":
        print("Cleaning up last build ...")
        args = ["rm", "-rf", "build"]
        subprocess.run(args, stdout=subprocess.PIPE)
        args = ["rm", "-rf", "dist"]
        subprocess.run(args, stdout=subprocess.PIPE)
        args = ["rm", "-rf", "turbo_seti.egg-info"]
        subprocess.run(args, stdout=subprocess.PIPE)
        args = ["rm", "-f", "turbo_seti/findoppler/taylor_tree.c"]
        subprocess.run(args, stdout=subprocess.PIPE)
        print("Clean up done")
        sys.exit(0)
```

I just tried it on turbo_seti and it worked without issues.

**Comment by texadactyl** [comment]
Note: there is no ```run``` function as part of ```subprocess``` in Python 2, just one of the many ways that migration is not always downwards compatible.

**Comment by texadactyl** [comment]
So, in Python2:

```
if len(sys.argv) == 2:
    if sys.argv[1] == "clean":
        print("Cleaning up last build ...")
        args = ["rm", "-rf", "build"]
        subprocess.call(args, stdout=subprocess.PIPE)
        args = ["rm", "-rf", "dist"]
        subprocess.call(args, stdout=subprocess.PIPE)
        args = ["rm", "-rf", "turbo_seti.egg-info"]
        subprocess.call(args, stdout=subprocess.PIPE)
        args = ["rm", "-f", "turbo_seti/findoppler/taylor_tree.c"]
        subprocess.call(args, stdout=subprocess.PIPE)
        print("Clean up done")
        sys.exit(0)
```

**Comment by texadactyl** [comment]
Sorry about that.  I should have tried this in both environments first before writing a comment here.

**Comment by texadactyl** [comment]
I consulted with a pal who has a Windows test machine.  This seems to work on Unix, Linux, and Windows:

1. Just before current line 1 in setup.py, insert:
```
import os
import shutil
import sys
```

2. Just before the setup() call, insert the following code block:
```
if len(sys.argv) == 2:
    if sys.argv[1] == "clean":
        print("Cleaning up last build ...")
        shutil.rmtree("build", ignore_errors=True)
        shutil.rmtree("dist", ignore_errors=True)
        shutil.rmtree("turbo_seti.egg-info", ignore_errors=True)
        try:
            os.remove("turbo_seti/findoppler/taylor_tree.c")
        except FileNotFoundError:
            pass
        print("Clean up done")
        sys.exit(0)
```

**Comment by texadactyl** [comment]
@jeenriquez No longer an issue in current github.

**Comment by telegraphic** [comment]
It appears this has been addressed. Closing issue
